Update Game.po
lvhuming/NoOneSurvivedTranslations pull request #152
Opened 2023-03-11 11:53 UTC by VarianGohl

2023-03-11 13:01 UTC, lindi200000 reviewed
@Welenkens please wait with merge

2023-03-11 17:11 UTC, Welenkens commented
Ok. Pay attention the confli

2023-03-13 10:27 UTC, Spyr0theDragon approved these changes

2023-03-13 12:14 UTC, lindi200000 requested changes
Please dont merge. 
We are still discussing "Zucht und Landwirtschaft" and then there is a conflict that needs to be resolved

2023-03-13 15:49 UTC, closed without merging